feat: add useComponentWillReceiveUpdate
SukkaW/foxact pull request #24
Opened 2024-10-10 14:28 UTC by Jack-Works

# useComponentWillReceiveUpdate

import ExportMetaInfo from '../components/export-meta-info';

<ExportMetaInfo />

Reset part of states when props changed.

## Usage

```js
import { useComponentWillReceiveUpdate } from 'foxact/use-abortable-effect';

function Component(props) {
  const [a, setA] = useState('')
  const [b, setB] = useState('')
  // when props.x changed, only reset a, not b
  useComponentWillReceiveUpdate(() => {
    setA('')
  }, [props.x]);
}
```

If you're using useEffect like this:

```js
  const [state, setState] = useState(false)
  useEffect(() => setState(false), [props.someProp])
```

Don't do it. See [Adjusting some state when a prop changes](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
It should be like this:
```js
  const [prev, setPrev] = useState(state)
  if (prev !== state) {
    setPrev(state)
    setState(false)
  }
```

This hook is a helper for the above pattern.

```js
useComponentWillReceiveUpdate(() => setState(false), [state])
```

This only applies to states of the current component.
Modifying states from other components causes React reporting errors.
You may also want to read [(Avoid) Notifying parent components about state changes](https://react.dev/learn/you-might-not-need-an-effect#notifying-parent-components-about-state-changes)
and [(Avoid) Passing data to the parent](https://react.dev/learn/you-might-not-need-an-effect#passing-data-to-the-parent).
If you really need to edit other components' states, write it like this:

```js
useComponentWillReceiveUpdate(() => {
  setLocalState(false)
  Promise.resolve().then(() => props.setParentState(false))
}, [state])
```

2024-10-10 14:30 UTC, SukkaW requested changes
Also mention the name of this hook comes from React Class Component: https://react.dev/reference/react/Component#unsafe_componentwillreceiveprops

2024-10-10 14:30 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +Don't do it. See [Adjusting some state when a prop changes](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
Should also mention https://react.dev/reference/react/useState#storing-information-from-previous-renders ?

2024-10-10 14:38 UTC, Jack-Works commented on docs/src/pages/use-component-will-receive-update.mdx
> +Don't do it. See [Adjusting some state when a prop changes](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
those two articles look the same, I think maybe no need for attach both

2024-10-10 14:43 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +Don't do it. See [Adjusting some state when a prop changes](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes)
IMHO we could link both. Also "information from previous render" definitely means more than "prop" alone.

2024-10-10 15:08 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +Reset part of states when props changed.
```suggestion
This hook allows you to change the state based on information from the previous render during a re-render. The name of the hook comes from [`UNSAFE_componentWillReceiveProps` method of class components](https://react.dev/reference/react/Component#unsafe_componentwillreceiveprops).
```

2024-10-10 15:13 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +  Promise.resolve().then(() => props.setParentState(false))
Use `flushSync` from React DOM is preferred: https://react.dev/reference/react-dom/flushSync

2024-10-10 15:23 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +Modifying states from other components causes React reporting errors.
Mention that this is your last resort when working with third-party libraries/components/SDKs.

2024-10-10 15:34 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +  setLocalState(false)
```suggestion
import { flushSync } from 'react-dom';

useComponentWillReceiveUpdate(() => {
  // Force React to immediately flush scheduled/batched updates
  flushSync(() => setLocalState(false))
  // By the time flushSync finishes and reaches this line, the DOM update
  // for local state change has finished, you can now safely trigger parent
  // components' re-render.
```

2024-10-11 02:34 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +useComponentWillReceiveUpdate(() => {
```suggestion
import { flushSync } from 'react-dom'

useComponentWillReceiveUpdate(() => {
```

2024-10-11 02:37 UTC, SukkaW commented on docs/src/pages/use-component-will-receive-update.mdx
> +If you need to edit other components' states, write it like this:
```suggestion
This should only apply to states of the current component. Modifying states of other components causes React reporting errors. You may also want to read [(Avoid) Notifying parent components about state changes](https://react.dev/learn/you-might-not-need-an-effect#notifying-parent-components-about-state-changes) and [(Avoid) Passing data to the parent](https://react.dev/learn/you-might-not-need-an-effect#passing-data-to-the-parent).

If you really need to directly modify other components' states (E.g. when working with third-party libraries/components/SDKs where you don't have control of that code), use `flushSync` to separate two state updates:
```

2024-10-11 02:37 UTC, merged