feat!: add force set value
SukkaW/foxact pull request #6
Opened 2023-07-25 03:50 UTC by AprilNEA

This will work well at certain times, such as  a search box(swr) with debounced input is submitted by the user.

```typescript
const Page = () => {
  const [debouncedKeyword, setDebouncedKeyword, forceSetValue] =
    useDebouncedState<string>("", 3000);

  const { data } = useSWR(
    debouncedKeyword ? ["/search", debouncedKeyword] : null,
    ([url, keyword]) =>
      fetch(url, {
        method: "POST",
        body: JSON.stringify({ keyword }),
      }).then((res) => res.json()),
  );

  return (
    ...
    <input onSumbit={(e)=> forceSetValue(e.target.value)} />
  )
}
```

I'm not sure this is correct or a best practice.

2023-07-25 04:53 UTC, SukkaW requested changes

2023-07-25 04:53 UTC, SukkaW commented on src/use-debounced-state/index.ts
> +import {useRetimer} from '../use-retimer';
Please do follow eslint rules and do not introduce any style changes.

2023-07-25 04:57 UTC, SukkaW requested changes

2023-07-25 04:57 UTC, SukkaW commented on src/use-retimer/index.ts
> +  return [retimer, clearRetimer] as const;
I do not want to change the `useRetimer`'s API design. Let's do this another way.

2023-07-25 12:29 UTC, AprilNEA commented on src/use-retimer/index.ts
> +  return [retimer, clearRetimer] as const;
Tried defining the clear attribute for the function, which would have been compatible with the original design, but perhaps not the best choice(?

2023-07-25 12:33 UTC, AprilNEA commented
Is the computational overhead here worth using `useMemo` like this?

```typescript
  const clear = useCallback(() => {
    clearTimeout(timerIdRef.current);
    timerIdRef.current = undefined;
  }, []);

  const retimerWithClear = useMemo(() => {
    const retimerFn = retimer as RetimerType;
    retimerFn.clear = clear;
    return retimerFn;
  }, [retimer, clear]);

  return retimerWithClear
```

2023-07-27 11:49 UTC, SukkaW commented on src/use-retimer/index.ts
> +  }, []) as RetimerType;
Is it possible to prevent `as` here?

2023-07-28 04:46 UTC, AprilNEA commented
Well, finally found what the problem is. 😭

2023-07-28 07:34 UTC, SukkaW approved these changes
LGTM now!

2023-07-28 07:36 UTC, merged